import type { CachedReportPayload } from "../types";

export const quizDemo: CachedReportPayload = {
  kind: "quiz",
  userId: "demo-user",
  generatedAt: "2026-05-23T18:24:00.000Z",
  aggregates: {
    sessionId: "demo-quiz-session",
    topicName: "Algebra",
    subtopicName: "Linear Equations in One Variable",
    score: 8,
    totalQuestions: 10,
    timeElapsedSeconds: 7 * 60 + 42,
    createdAt: "2026-05-23T18:24:00.000Z",
    accuracy: 0.8,
    meanResponseTimeMs: 38_400,
    medianResponseTimeMs: 32_100,
    hintRate: 0.3,
    tutorRate: 0.2,
    recoveryRate: 1.0,
    perQuestion: [
      { index: 0, problemId: "p1", isCorrect: true, responseTimeMs: 24_000, wrongCount: 0, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 3 },
      { index: 1, problemId: "p2", isCorrect: true, responseTimeMs: 19_500, wrongCount: 0, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 4 },
      { index: 2, problemId: "p3", isCorrect: false, responseTimeMs: 81_200, wrongCount: 2, hintUsed: true, tutorUsed: true, practiceCompleted: true, difficultyLevel: 7 },
      { index: 3, problemId: "p4", isCorrect: true, responseTimeMs: 33_800, wrongCount: 1, hintUsed: true, tutorUsed: false, practiceCompleted: false, difficultyLevel: 5 },
      { index: 4, problemId: "p5", isCorrect: true, responseTimeMs: 28_900, wrongCount: 0, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 4 },
      { index: 5, problemId: "p6", isCorrect: false, responseTimeMs: 92_400, wrongCount: 2, hintUsed: true, tutorUsed: true, practiceCompleted: true, difficultyLevel: 8 },
      { index: 6, problemId: "p7", isCorrect: true, responseTimeMs: 41_100, wrongCount: 0, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 6 },
      { index: 7, problemId: "p8", isCorrect: true, responseTimeMs: 26_700, wrongCount: 0, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 5 },
      { index: 8, problemId: "p9", isCorrect: true, responseTimeMs: 31_200, wrongCount: 1, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 6 },
      { index: 9, problemId: "p10", isCorrect: true, responseTimeMs: 47_500, wrongCount: 0, hintUsed: false, tutorUsed: false, practiceCompleted: false, difficultyLevel: 7 },
    ],
    events: {
      answerWrong: 6,
      hintShown: 3,
      tutorEntered: 2,
      tutorCorrect: 2,
      practiceStarted: 2,
      practiceCorrect: 4,
      practiceExhausted: 0,
    },
    skill: { level: 5, xp: 1240, streakCorrect: 3, streakWrong: 0 },
  },
  analysis: {
    headline: "Strong showing on the basics",
    scoreContext: "Solid 8 of 10 — both misses came from harder problems where pacing slowed you down.",
    strengths: [
      { icon: "zap", label: "Fast on easy items", detail: "Sub-30s on level 3–5 problems." },
      { icon: "trending-up", label: "Recovered after each miss", detail: "Practice problems hit 100%." },
      { icon: "shield-check", label: "Clean first attempts", detail: "7 of 10 right on the first try." },
    ],
    growthAreas: [
      { icon: "clock", label: "Slowing on difficulty 7+", detail: "Mean response time doubled on the hardest items." },
      { icon: "scale", label: "Sign-flip on inequalities", detail: "Tutor chat surfaced this twice." },
      { icon: "telescope", label: "Read the full constraint", detail: "Missed a domain restriction on problem 6." },
    ],
    speedInsight: "Your median was 32s — well under the 60s target for SAT linear-equation items.",
    nextStepSuggestion: "Run the 'Inequalities' subtopic next; that's where your speed dropped most sharply.",
  },
};
