import { supabase } from "@/lib/supabase/client";
import type { Json } from "@/types/supabase";

/** One question in a structured practice-set assignment (pulled from the
 *  Athena problem bank). `correctIndex`/`explanation` are teacher-only —
 *  strip them before anything student-facing. */
export interface AssignmentQuestion {
  id: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string | null;
}

/** Student-safe projection of AssignmentQuestion. */
export interface PublicAssignmentQuestion {
  id: string;
  prompt: string;
  options: string[];
}

/** One question in a free-response quiz (generated by "Write with AI").
 *  `answer` is the teacher-only expected solution/rubric — strip it before
 *  anything student-facing. Discriminated from multiple-choice practice-set
 *  questions by `kind: "free"`. */
export interface FreeResponseQuestion {
  id: string;
  kind: "free";
  prompt: string;
  answer: string;
}

/** Student-safe projection of FreeResponseQuestion. */
export interface PublicFreeResponseQuestion {
  id: string;
  kind: "free";
  prompt: string;
}

/** An assignment's `questions` jsonb is either a multiple-choice practice set
 *  or a free-response quiz — never a mix. */
export type QuizQuestion = AssignmentQuestion | FreeResponseQuestion;
export type PublicQuizQuestion =
  | PublicAssignmentQuestion
  | PublicFreeResponseQuestion;

/** A class/section. `class_id` FKs on students/assignments are nullable
 *  (ON DELETE SET NULL): deleting a class leaves its work "unassigned". */
export interface EducatorClass {
  id: string;
  name: string;
  createdAt: string;
}

export interface EducatorAssignment {
  id: string;
  title: string;
  instructions: string;
  /** Teacher-only. Never returned by the public assignment endpoint. */
  answerKey: string | null;
  /** Multiple-choice practice set, free-response quiz, or null (text homework). */
  questions: QuizQuestion[] | null;
  /** Owning class, or null when unassigned. */
  classId: string | null;
  assignedDate: string; // YYYY-MM-DD — the day the work is handed out
  dueDate: string; // YYYY-MM-DD
  source: string;
  prompt: string | null;
  createdAt: string;
}

export interface EducatorStudent {
  id: string;
  name: string;
  studentEmail: string;
  parentEmail: string;
  /** Owning class, or null when unassigned. */
  classId: string | null;
  createdAt: string;
}

export interface EducatorSubmission {
  id: string;
  assignmentId: string;
  studentId: string;
  response: string | null;
  /** Chosen option index per question (practice-set submissions). */
  answers: number[] | null;
  /** Storage paths of student work photos (educator-work bucket). */
  images: string[] | null;
  /** Short-lived signed URLs for the teacher view; populated by
   *  listSubmissionsForTeacher only. */
  imageUrls?: string[];
  grade: number | null;
  /** The AI grader's feedback. */
  feedback: string | null;
  /** The teacher's own feedback, kept separate from the AI's. */
  teacherFeedback: string | null;
  /** True when the response was AI-invented via the explicit demo action. */
  simulated: boolean;
  submittedAt: string | null;
  gradedAt: string | null;
}

export interface ParentReport {
  id: string;
  studentId: string;
  periodStart: string;
  periodEnd: string;
  summary: string | null;
  sentAt: string;
}

const ASSIGNMENT_COLS =
  "id, title, instructions, answer_key, questions, class_id, assigned_date, due_date, source, prompt, created_at";
const STUDENT_COLS =
  "id, name, student_email, parent_email, class_id, created_at";
const SUBMISSION_COLS =
  "id, assignment_id, student_id, response, answers, images, grade, feedback, teacher_feedback, simulated, submitted_at, graded_at";

const WORK_BUCKET = "educator-work";

function mapAssignment(row: {
  id: string;
  title: string;
  instructions: string;
  answer_key: string | null;
  questions: Json | null;
  class_id: string | null;
  assigned_date: string;
  due_date: string;
  source: string;
  prompt: string | null;
  created_at: string;
}): EducatorAssignment {
  return {
    id: row.id,
    title: row.title,
    instructions: row.instructions,
    answerKey: row.answer_key,
    questions: (row.questions as unknown as QuizQuestion[] | null) ?? null,
    classId: row.class_id,
    assignedDate: row.assigned_date,
    dueDate: row.due_date,
    source: row.source,
    prompt: row.prompt,
    createdAt: row.created_at,
  };
}

function mapStudent(row: {
  id: string;
  name: string;
  student_email: string;
  parent_email: string;
  class_id: string | null;
  created_at: string;
}): EducatorStudent {
  return {
    id: row.id,
    name: row.name,
    studentEmail: row.student_email,
    parentEmail: row.parent_email,
    classId: row.class_id,
    createdAt: row.created_at,
  };
}

function mapClass(row: {
  id: string;
  name: string;
  created_at: string;
}): EducatorClass {
  return { id: row.id, name: row.name, createdAt: row.created_at };
}

function mapSubmission(row: {
  id: string;
  assignment_id: string;
  student_id: string;
  response: string | null;
  answers: Json | null;
  images: Json | null;
  grade: number | null;
  feedback: string | null;
  teacher_feedback: string | null;
  simulated: boolean;
  submitted_at: string | null;
  graded_at: string | null;
}): EducatorSubmission {
  return {
    id: row.id,
    assignmentId: row.assignment_id,
    studentId: row.student_id,
    response: row.response,
    answers: (row.answers as unknown as number[] | null) ?? null,
    images: (row.images as unknown as string[] | null) ?? null,
    grade: row.grade,
    feedback: row.feedback,
    teacherFeedback: row.teacher_feedback,
    simulated: row.simulated,
    submittedAt: row.submitted_at,
    gradedAt: row.graded_at,
  };
}

// ─── Classes ─────────────────────────────────────────────────────────────

export async function listClasses(teacherId: string) {
  const { data, error } = await supabase
    .from("educator_classes")
    .select("id, name, created_at")
    .eq("teacher_id", teacherId)
    .order("created_at", { ascending: true });
  if (error) throw error;
  return (data ?? []).map(mapClass);
}

export async function createClass(teacherId: string, name: string) {
  const { data, error } = await supabase
    .from("educator_classes")
    .insert({ teacher_id: teacherId, name })
    .select("id, name, created_at")
    .single();
  if (error) throw error;
  return mapClass(data);
}

export async function renameClass(teacherId: string, id: string, name: string) {
  const { data, error } = await supabase
    .from("educator_classes")
    .update({ name })
    .eq("teacher_id", teacherId)
    .eq("id", id)
    .select("id, name, created_at")
    .maybeSingle();
  if (error) throw error;
  return data ? mapClass(data) : null;
}

/** Delete a class. The FK is ON DELETE SET NULL, so its students and
 *  assignments survive as "unassigned" — no cascading data loss. */
export async function deleteClass(teacherId: string, id: string) {
  const { error } = await supabase
    .from("educator_classes")
    .delete()
    .eq("teacher_id", teacherId)
    .eq("id", id);
  if (error) throw error;
}

/** Update a student's editable fields. `classId: null` unassigns; omit a
 *  field to leave it unchanged. */
export async function updateStudent(
  teacherId: string,
  studentId: string,
  patch: {
    name?: string;
    studentEmail?: string;
    parentEmail?: string;
    classId?: string | null;
  }
) {
  const update: Record<string, unknown> = {};
  if (patch.name !== undefined) update.name = patch.name;
  if (patch.studentEmail !== undefined) update.student_email = patch.studentEmail;
  if (patch.parentEmail !== undefined) update.parent_email = patch.parentEmail;
  if (patch.classId !== undefined) update.class_id = patch.classId;
  const { data, error } = await supabase
    .from("educator_students")
    .update(update)
    .eq("teacher_id", teacherId)
    .eq("id", studentId)
    .select(STUDENT_COLS)
    .maybeSingle();
  if (error) throw error;
  return data ? mapStudent(data) : null;
}

// ─── Assignments ─────────────────────────────────────────────────────────

export async function listAssignments(teacherId: string) {
  const { data, error } = await supabase
    .from("educator_assignments")
    .select(ASSIGNMENT_COLS)
    .eq("teacher_id", teacherId)
    .order("due_date", { ascending: true });
  if (error) throw error;
  return (data ?? []).map(mapAssignment);
}

export async function getAssignment(teacherId: string, id: string) {
  const { data, error } = await supabase
    .from("educator_assignments")
    .select(ASSIGNMENT_COLS)
    .eq("teacher_id", teacherId)
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return data ? mapAssignment(data) : null;
}

/** Student-facing fetch by share link — no teacher scoping, public fields
 *  only. The answer key is never selected and practice-set questions are
 *  stripped to their student-safe projection. */
export async function getPublicAssignment(id: string) {
  const { data, error } = await supabase
    .from("educator_assignments")
    .select("id, title, instructions, due_date, questions")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  if (!data) return null;
  const questions =
    (data.questions as unknown as QuizQuestion[] | null) ?? null;
  // Strip teacher-only fields per question kind: `answer` for free-response,
  // `correctIndex`/`explanation` for multiple-choice.
  const publicQuestions: PublicQuizQuestion[] | null = questions
    ? questions.map((q) =>
        "kind" in q && q.kind === "free"
          ? { id: q.id, kind: "free", prompt: q.prompt }
          : {
              id: q.id,
              prompt: q.prompt,
              options: (q as AssignmentQuestion).options,
            }
      )
    : null;
  return {
    id: data.id,
    title: data.title,
    instructions: data.instructions,
    dueDate: data.due_date,
    questions: publicQuestions,
  };
}

/** Internal fetch for the public submit endpoint: includes teacher_id (to
 *  match the student against the right roster) and full questions (to grade
 *  objectively). Never return this shape to a client. */
export async function getAssignmentForSubmit(id: string) {
  const { data, error } = await supabase
    .from("educator_assignments")
    .select("id, teacher_id, title, questions")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  if (!data) return null;
  return {
    id: data.id,
    teacherId: data.teacher_id,
    title: data.title,
    questions: (data.questions as unknown as QuizQuestion[] | null) ?? null,
  };
}

export async function createAssignment(data: {
  teacherId: string;
  title: string;
  instructions: string;
  answerKey?: string | null;
  questions?: QuizQuestion[] | null;
  classId?: string | null;
  assignedDate?: string;
  dueDate: string;
  source?: string;
  prompt?: string | null;
}) {
  const { data: row, error } = await supabase
    .from("educator_assignments")
    .insert({
      teacher_id: data.teacherId,
      title: data.title,
      instructions: data.instructions,
      answer_key: data.answerKey ?? null,
      questions: (data.questions ?? null) as unknown as Json,
      class_id: data.classId ?? null,
      // Omit when unset so the column default (today, UTC) applies.
      ...(data.assignedDate ? { assigned_date: data.assignedDate } : {}),
      due_date: data.dueDate,
      source: data.source ?? "ai",
      prompt: data.prompt ?? null,
    })
    .select(ASSIGNMENT_COLS)
    .single();
  if (error) throw error;
  return mapAssignment(row);
}

export async function updateAssignment(
  teacherId: string,
  id: string,
  patch: {
    title?: string;
    instructions?: string;
    answerKey?: string | null;
    classId?: string | null;
    assignedDate?: string;
    dueDate?: string;
  }
) {
  const update: Record<string, unknown> = {};
  if (patch.title !== undefined) update.title = patch.title;
  if (patch.instructions !== undefined) update.instructions = patch.instructions;
  if (patch.answerKey !== undefined) update.answer_key = patch.answerKey;
  if (patch.classId !== undefined) update.class_id = patch.classId;
  if (patch.assignedDate !== undefined) update.assigned_date = patch.assignedDate;
  if (patch.dueDate !== undefined) update.due_date = patch.dueDate;
  const { data: row, error } = await supabase
    .from("educator_assignments")
    .update(update)
    .eq("teacher_id", teacherId)
    .eq("id", id)
    .select(ASSIGNMENT_COLS)
    .maybeSingle();
  if (error) throw error;
  return row ? mapAssignment(row) : null;
}

export async function deleteAssignment(teacherId: string, id: string) {
  const { error } = await supabase
    .from("educator_assignments")
    .delete()
    .eq("teacher_id", teacherId)
    .eq("id", id);
  if (error) throw error;
}

// ─── Students ────────────────────────────────────────────────────────────

export async function listStudents(teacherId: string) {
  const { data, error } = await supabase
    .from("educator_students")
    .select(STUDENT_COLS)
    .eq("teacher_id", teacherId)
    .order("name");
  if (error) throw error;
  return (data ?? []).map(mapStudent);
}

export async function getStudent(teacherId: string, id: string) {
  const { data, error } = await supabase
    .from("educator_students")
    .select(STUDENT_COLS)
    .eq("teacher_id", teacherId)
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return data ? mapStudent(data) : null;
}

/** Case-insensitive roster lookup by school email (the share-link submit
 *  flow's identity key). */
export async function findStudentByEmail(teacherId: string, email: string) {
  const { data, error } = await supabase
    .from("educator_students")
    .select(STUDENT_COLS)
    .eq("teacher_id", teacherId)
    .ilike("student_email", email.trim())
    .maybeSingle();
  if (error) throw error;
  return data ? mapStudent(data) : null;
}

export async function createStudent(data: {
  teacherId: string;
  name: string;
  studentEmail: string;
  parentEmail: string;
  classId?: string | null;
}) {
  const { data: row, error } = await supabase
    .from("educator_students")
    .insert({
      teacher_id: data.teacherId,
      name: data.name,
      student_email: data.studentEmail,
      parent_email: data.parentEmail,
      class_id: data.classId ?? null,
    })
    .select(STUDENT_COLS)
    .single();
  if (error) throw error;
  return mapStudent(row);
}

export async function deleteStudent(teacherId: string, id: string) {
  const { error } = await supabase
    .from("educator_students")
    .delete()
    .eq("teacher_id", teacherId)
    .eq("id", id);
  if (error) throw error;
}

/** Link a roster entry to a real Athena account (set once, when the student
 *  first signs in to do homework). Never overwrites an existing link. */
export async function linkStudentToUser(studentId: string, userId: string) {
  const { error } = await supabase
    .from("educator_students")
    .update({ user_id: userId })
    .eq("id", studentId)
    .is("user_id", null);
  if (error) throw error;
}

// ─── Submission work photos (educator-work bucket) ──────────────────────

const EXT_BY_MIME: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

export interface SubmissionImageUpload {
  mediaType: string;
  /** base64 (no data: prefix) */
  data: string;
}

/** Store a student's work photos, replacing any photos from a previous
 *  submission of the same (assignment, student) pair. Returns storage paths. */
export async function uploadSubmissionImages(
  assignmentId: string,
  studentId: string,
  images: SubmissionImageUpload[]
) {
  const prefix = `${assignmentId}/${studentId}`;
  // Clear out the previous attempt so storage doesn't accumulate orphans.
  const { data: existing } = await supabase.storage
    .from(WORK_BUCKET)
    .list(prefix);
  if (existing?.length) {
    await supabase.storage
      .from(WORK_BUCKET)
      .remove(existing.map((f) => `${prefix}/${f.name}`));
  }

  const stamp = Date.now();
  const paths: string[] = [];
  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    const ext = EXT_BY_MIME[img.mediaType];
    if (!ext) throw new Error(`Unsupported image type: ${img.mediaType}`);
    const path = `${prefix}/${stamp}-${i}.${ext}`;
    const { error } = await supabase.storage
      .from(WORK_BUCKET)
      .upload(path, Buffer.from(img.data, "base64"), {
        contentType: img.mediaType,
        upsert: true,
      });
    if (error) throw error;
    paths.push(path);
  }
  return paths;
}

/** Short-lived signed URLs for the teacher view. Returns a path→url map. */
export async function signWorkImages(paths: string[]) {
  if (paths.length === 0) return new Map<string, string>();
  const { data, error } = await supabase.storage
    .from(WORK_BUCKET)
    .createSignedUrls(paths, 3600);
  if (error) throw error;
  const map = new Map<string, string>();
  (data ?? []).forEach((d) => {
    if (d.path && d.signedUrl) map.set(d.path, d.signedUrl);
  });
  return map;
}

/** Download a stored work photo as base64 for the vision grading call. */
export async function downloadWorkImageB64(path: string) {
  const { data, error } = await supabase.storage.from(WORK_BUCKET).download(path);
  if (error) throw error;
  const buf = Buffer.from(await data.arrayBuffer());
  const ext = path.split(".").pop() ?? "jpg";
  const mediaType =
    Object.entries(EXT_BY_MIME).find(([, e]) => e === ext)?.[0] ?? "image/jpeg";
  return { mediaType, data: buf.toString("base64") };
}

// ─── Submissions ─────────────────────────────────────────────────────────

export async function listSubmissionsForTeacher(teacherId: string) {
  const { data, error } = await supabase
    .from("educator_submissions")
    .select(`${SUBMISSION_COLS}, educator_assignments!inner(teacher_id)`)
    .eq("educator_assignments.teacher_id", teacherId);
  if (error) throw error;
  const submissions = (data ?? []).map(mapSubmission);

  // One batch signing call across every photo in the class.
  const allPaths = submissions.flatMap((s) => s.images ?? []);
  if (allPaths.length) {
    const signed = await signWorkImages(allPaths);
    submissions.forEach((s) => {
      if (s.images?.length) {
        s.imageUrls = s.images
          .map((p) => signed.get(p))
          .filter((u): u is string => !!u);
      }
    });
  }
  return submissions;
}

export async function findSubmission(assignmentId: string, studentId: string) {
  const { data, error } = await supabase
    .from("educator_submissions")
    .select(SUBMISSION_COLS)
    .eq("assignment_id", assignmentId)
    .eq("student_id", studentId)
    .maybeSingle();
  if (error) throw error;
  return data ? mapSubmission(data) : null;
}

/** Real student work arriving through the share link. Replaces any previous
 *  submission and clears the grade — new work needs a fresh grading pass
 *  (practice sets pass their objective grade in directly). */
export async function submitStudentWork(data: {
  assignmentId: string;
  studentId: string;
  userId?: string | null;
  response: string | null;
  answers: number[] | null;
  images: string[] | null;
  grade: number | null;
  feedback: string | null;
}) {
  const existing = await findSubmission(data.assignmentId, data.studentId);
  const now = new Date().toISOString();
  const { data: row, error } = await supabase
    .from("educator_submissions")
    .upsert(
      {
        ...(existing ? { id: existing.id } : {}),
        assignment_id: data.assignmentId,
        student_id: data.studentId,
        user_id: data.userId ?? null,
        response: data.response,
        answers: (data.answers ?? null) as unknown as Json,
        images: (data.images ?? null) as unknown as Json,
        grade: data.grade,
        feedback: data.feedback,
        simulated: false,
        submitted_at: now,
        graded_at: data.grade !== null ? now : null,
      },
      { onConflict: "assignment_id,student_id" }
    )
    .select(SUBMISSION_COLS)
    .single();
  if (error) throw error;
  return mapSubmission(row);
}

/** AI grading of an existing (real or simulated) response: only the
 *  evaluation fields change — the student's response is never rewritten. */
export async function applyAiGradeToSubmission(data: {
  submissionId: string;
  grade: number | null;
  feedback: string;
}) {
  const { data: row, error } = await supabase
    .from("educator_submissions")
    .update({
      grade: data.grade,
      feedback: data.feedback,
      graded_at: new Date().toISOString(),
    })
    .eq("id", data.submissionId)
    .select(SUBMISSION_COLS)
    .single();
  if (error) throw error;
  return mapSubmission(row);
}

/** Explicit demo action: store an AI-invented response + grade, marked
 *  simulated so it is badged and excluded from real statistics. Never
 *  overwrites a real submission. */
export async function applySimulatedSubmission(data: {
  assignmentId: string;
  studentId: string;
  response: string;
  grade: number | null;
  feedback: string;
}) {
  const existing = await findSubmission(data.assignmentId, data.studentId);
  if (existing && !existing.simulated) {
    throw new Error("Student already has a real submission");
  }
  const now = new Date().toISOString();
  const { data: row, error } = await supabase
    .from("educator_submissions")
    .upsert(
      {
        ...(existing ? { id: existing.id } : {}),
        assignment_id: data.assignmentId,
        student_id: data.studentId,
        response: data.response,
        answers: null,
        images: null,
        grade: data.grade,
        feedback: data.feedback,
        simulated: true,
        submitted_at: existing?.submittedAt ?? now,
        graded_at: now,
      },
      { onConflict: "assignment_id,student_id" }
    )
    .select(SUBMISSION_COLS)
    .single();
  if (error) throw error;
  return mapSubmission(row);
}

/** Manual teacher edit: grade + the teacher's own feedback change. The AI
 *  feedback (`feedback` column), the response, and the simulated flag are all
 *  preserved. */
export async function saveSubmissionEdit(data: {
  assignmentId: string;
  studentId: string;
  grade: number | null;
  teacherFeedback: string;
}) {
  const existing = await findSubmission(data.assignmentId, data.studentId);
  const now = new Date().toISOString();
  if (existing) {
    const { data: row, error } = await supabase
      .from("educator_submissions")
      .update({
        grade: data.grade,
        teacher_feedback: data.teacherFeedback,
        graded_at: now,
      })
      .eq("id", existing.id)
      .select(SUBMISSION_COLS)
      .single();
    if (error) throw error;
    return mapSubmission(row);
  }
  const { data: row, error } = await supabase
    .from("educator_submissions")
    .insert({
      assignment_id: data.assignmentId,
      student_id: data.studentId,
      grade: data.grade,
      teacher_feedback: data.teacherFeedback,
      simulated: false,
      submitted_at: now,
      graded_at: now,
    })
    .select(SUBMISSION_COLS)
    .single();
  if (error) throw error;
  return mapSubmission(row);
}

// ─── Parent reports ──────────────────────────────────────────────────────

export async function logParentReport(data: {
  teacherId: string;
  studentId: string;
  periodStart: string;
  periodEnd: string;
  summary: string;
}) {
  const { error } = await supabase.from("educator_parent_reports").insert({
    teacher_id: data.teacherId,
    student_id: data.studentId,
    period_start: data.periodStart,
    period_end: data.periodEnd,
    summary: data.summary,
  });
  if (error) throw error;
}

export async function listParentReports(teacherId: string, studentId: string) {
  const { data, error } = await supabase
    .from("educator_parent_reports")
    .select("id, student_id, period_start, period_end, summary, sent_at")
    .eq("teacher_id", teacherId)
    .eq("student_id", studentId)
    .order("sent_at", { ascending: false })
    .limit(12);
  if (error) throw error;
  return (data ?? []).map(
    (r): ParentReport => ({
      id: r.id,
      studentId: r.student_id,
      periodStart: r.period_start,
      periodEnd: r.period_end,
      summary: r.summary,
      sentAt: r.sent_at,
    })
  );
}
