-- Add nullable question_phonetic column to problems table.
-- This is a TTS-ready prose version of question_text: LaTeX (e.g. $...$),
-- variables, operators, fractions, and exponents are spelled out as English
-- phrases so a speech synthesizer can read practice-quiz questions cleanly.
-- Generated by the model alongside question_text at seeding time, and
-- backfilled for already-seeded problems by .local/backfill-practice-phonetic.ts.
-- Idempotent: safe to re-run.

ALTER TABLE problems
  ADD COLUMN IF NOT EXISTS question_phonetic text;

COMMENT ON COLUMN problems.question_phonetic IS
  'TTS-ready phonetic English version of question_text. NULL when not yet generated. LaTeX, variables, operators, and exponents are spelled out (e.g. "x squared plus three" instead of "$x^2 + 3$").';
