-- ===========================================================
-- Podcast scripts — one structured-dialogue script per subtopic.
--
-- Generated by the podcast_agent in agents/ and persisted from
-- the Next.js orchestrator route. Shared across users: one
-- subtopic = one script, like micro_lessons.
--
-- `speakers` is a jsonb list of {id, name, role, bio?}.
-- `lines` is a jsonb list of {speaker_id, text, tone_hint?}.
-- The Pydantic schema in agents/app/run_time/sat/podcast_agent.py
-- is the source of truth for the JSON shape — this table stores
-- the post-validation dump.
--
-- NOTE: This migration must be applied via the Supabase Studio
-- SQL editor due to migration drift on the remote (see memory:
-- project_migration_drift_april2026.md). Committed here for
-- traceability.
-- ===========================================================

CREATE TABLE IF NOT EXISTS "podcast_scripts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subtopic_id" uuid NOT NULL,
	"title" text NOT NULL,
	"summary" text NOT NULL,
	"speakers" jsonb NOT NULL,
	"lines" jsonb NOT NULL,
	"has_guest" boolean NOT NULL DEFAULT false,
	"estimated_duration_minutes" double precision,
	"status" text DEFAULT 'generating' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "podcast_scripts_subtopic_id_unique" UNIQUE ("subtopic_id")
);

ALTER TABLE "podcast_scripts"
	ADD CONSTRAINT "podcast_scripts_subtopic_id_subtopics_id_fk"
	FOREIGN KEY ("subtopic_id") REFERENCES "public"."subtopics"("id")
	ON DELETE cascade ON UPDATE no action;

-- Default-deny RLS. Reads/writes happen through service-role
-- server code (the Next.js orchestrator at
-- /api/podcast/[subtopicId]); there is no direct per-user
-- access pattern. Shared content, no per-user rows.
ALTER TABLE "podcast_scripts" ENABLE ROW LEVEL SECURITY;
